avid: set random access bit in edit unit flag even if open gop
According to SMPTE ST-381 bit 7 shall not be set if the GOP is
Open. However, in Avid OP-Atom files this bit must be set because
otherwise it assumes the precharge is right back to the first frame
(which has a Closed GOP), but doesn't get the index table correct
resulting in this error:
    Exception: MXF_DIDMapper::ReadRange - End Sample Index exceeds
               on-disk Index Entry Count.